name: Semgrep Security Scan

on:
  workflow_dispatch:

jobs:
  semgrep:
    name: Run Semgrep Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python (for Semgrep)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan (non-blocking)
        run: |
          mkdir -p semgrep_reports
          semgrep --config auto --json --output semgrep_reports/semgrep-report.json || true

      - name: Upload Semgrep JSON report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep_reports/semgrep-report.json
